export const paths = {
  home: "/",
  login: "/login",
  register: "/register",
  menu: "/menu",
  machines: "/machines",
  users: "/users",
  projects: "/projects",
  components: "/components",
  commissioning: "/commissioning",
  audit: "/audit",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  codeVerification: "/code-verification",
};
